show databases;
use bootcamp_2408_test;
show tables;
select * from users;
select count(*) from users;
select * from posts;
select count(*) from posts;
select * from comments;
select count(*) from comments;
drop table if exists users;
drop table if exists posts;
drop table if exists comments;
select * from comments where id = 999;
delete from comments where id = 1;
select * from posts where id = 1;
delete from posts where id = 1;
insert into comments values (999, 9, "abcTesting", "abc@gmail.com", "naming nane");
